version: "3.8"

services:
  evilportal:
    build: .
    container_name: evil_portal
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/www/html/captiveportal/logs
    restart: unless-stopped
    networks:
      - portalnet

networks:
  portalnet:
    driver: bridge
